### ISSUE TITLE
为什么serverBootstrap中initChannel的时候，encoder和decoder连在一起，然后再是NettyServerHandler？

### ISSUE THREAD

**Issue by tang-world** [CN-GuoZiyang/My-RPC-Framework#6]
我在commit ：《 统一Netty与传统IO方式的操作接口，Socket方式也可使用多种序列化器 》 ，这里有一个问题
为什么serverBootstrap中initChannel的时候，encoder和decoder连在一起，然后再是NettyServerHandler？
这样不会是inHead -> encoder -> decoder->handler->tail的吗?
我认为应该是 inHead->decoder->handler->encoder->tail，请问我是哪里没有注意到呢？

**Comment by CN-GuoZiyang** [comment]
连在一起，但是一个是Inbound一个是outbound，都只会处理对应方向的数据，会忽略掉方向不同的数据

**Comment by CN-GuoZiyang** [comment]
所以整个处理流程是这样的

外部 -> encoder(忽略) -> decoder - -
                                                               |
                                                             handler
                                                               |
外部 <- encoder <- decoder(忽略) - -
